### ISSUE TITLE
Where is the writer module? regression

### ISSUE THREAD

**Issue by lotashah** [onelogin/onelogin-python-aws-assume-role#30]
Using master branch at revision 670a59e9fe4e0fc52beef966b8257254b183e823 in a clean Ubuntu 18.04.2 install with python 2.7.15rc1, following [the Quick Start](https://github.com/onelogin/onelogin-python-aws-assume-role#quick-start-using-the-python-scrypt) running in virtualenv

receive import error

```
(venv) user@ubuntu:/tmp/onelogin-python-aws-assume-role$ onelogin-aws-assume-role --help
Traceback (most recent call last):
  File "/tmp/onelogin-python-aws-assume-role/venv/bin/onelogin-aws-assume-role", line 11, in <module>
    load_entry_point('onelogin-aws-assume-role', 'console_scripts', 'onelogin-aws-assume-role')()
  File "/tmp/onelogin-python-aws-assume-role/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/onelogin-python-aws-assume-role/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/tmp/onelogin-python-aws-assume-role/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/tmp/onelogin-python-aws-assume-role/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/onelogin-python-aws-assume-role/src/aws_assume_role/aws_assume_role.py", line 17, in <module>
    from aws_assume_role.writer import ConfigFileWriter
ImportError: No module named writer

```

if i revert issue #26 commit 474f8ed1d980654e80c56bc68c5daa189ca4f29b, then all is well

```
(venv) user@host:/tmp/onelogin-python-aws-assume-role$ onelogin-aws-assume-role --help

OneLogin AWS Assume Role Tool

usage: onelogin-aws-assume-role [-h] [-i CLIENT_ID] [-s CLIENT_SECRET]
                                [-r REGION] [-t TIME] [-l LOOP]
                                [-p PROFILE_NAME] [-f FILE] [-u USERNAME]
                                [--onelogin-password PASSWORD] [-a APP_ID]
                                [-d SUBDOMAIN] [-z DURATION] [-x INTERACTIVE]
                                [--aws-region AWS_REGION]
                                [--aws-account-id AWS_ACCOUNT_ID]
                                [--aws-role-name AWS_ROLE_NAME]

```

**Comment by pitbulk** [comment]
I'm still investigating what is the issue.

It seems that if you use the package from pypi, it requires 
```
from aws_assume_role.writer import ConfigFileWriter
```
but if you are using the code directly from the repository, then it requires
```
from writer import ConfigFileWriter
```
