### ISSUE TITLE
Onelogin Cli integration failure

### ISSUE THREAD

**Issue by avnerv** [onelogin/onelogin-python-aws-assume-role#60]
Hi,
I'm trying to install and configure the onelogin-aws-assume-role (in both python and java) and received the below error message:
**Exception in thread "main" OAuthProblemException{error='error', description='App could not be found', uri='null', state='404', scope='null', redirectUri='null', responseStatus=404, parameters={}}
	at org.apache.oltu.oauth2.common.exception.OAuthProblemException.error(OAuthProblemException.java:59)
	at org.apache.oltu.oauth2.client.validator.OAuthClientValidator.validateErrorResponse(OAuthClientValidator.java:63)
	at org.apache.oltu.oauth2.client.validator.OAuthClientValidator.validate(OAuthClientValidator.java:48)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponse.validate(OAuthClientResponse.java:127)
	at com.onelogin.sdk.conn.OneloginOAuthJSONResourceResponse.init(OneloginOAuthJSONResourceResponse.java:31)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponse.init(OAuthClientResponse.java:101)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponse.init(OAuthClientResponse.java:120)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponseFactory.createCustomResponse(OAuthClientResponseFactory.java:82)
	at com.onelogin.sdk.conn.OneloginURLConnectionClient.execute(OneloginURLConnectionClient.java:75)
	at org.apache.oltu.oauth2.client.OAuthClient.resource(OAuthClient.java:81)
	at com.onelogin.sdk.conn.Client.getSAMLAssertion(Client.java:2238)
	at com.onelogin.aws.assume.role.cli.OneloginAWSCLI.getSamlResponse(OneloginAWSCLI.java:437)
	at com.onelogin.aws.assume.role.cli.OneloginAWSCLI.main(OneloginAWSCLI.java:256)
➜  onelogin-sso java -jar onelogin-aws-cli.jar**

I have used this procedure - https://developers.onelogin.com/api-docs/1/samples/aws-cli 
Please help.

Thanks,
Avner

**Comment by pitbulk** [comment]
That error is a java error trace, so you can't have it executing the python aws-cli.

That said, if you read the error, you can find:  "App could not be found"  so basically, you configured the aws-cli with an appid that does not exists in your OL account.
